//
// CustomerUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CustomerUser: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Related *Customer* primary key */
    public var customerId: String?
    /** Related *CustomerLocation* primary key */
    public var customerLocationId: String?
    /** First name */
    public var firstName: String?
    /** Last name */
    public var lastName: String?
    /** Full name */
    public var fullName: String?
    /** Email */
    public var email: String?
    /** Mobile/SMS phone */
    public var smsNumber: String?
    /** Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** Language (ISO-2) */
    public var lang: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["customer_id"] = self.customerId
        nillableDictionary["customer_location_id"] = self.customerLocationId
        nillableDictionary["first_name"] = self.firstName
        nillableDictionary["last_name"] = self.lastName
        nillableDictionary["full_name"] = self.fullName
        nillableDictionary["email"] = self.email
        nillableDictionary["sms_number"] = self.smsNumber
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["lang"] = self.lang

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

