//
// CustomerTechnology.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CustomerTechnology: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** The primary key of the related *CustomerTechnology* */
    public var parentId: String?
    /** The primary key of the related *Customer* */
    public var customerId: String?
    /** The primary key of the related *CustomerLocation* */
    public var customerLocationId: String?
    /** The primary key of the related *Org* */
    public var orgId: String?
    /** chat nickname */
    public var nickname: String?
    /** technology type */
    public var type: String?
    /** Is device in critical status */
    public var critical: Bool?
    /** is active */
    public var active: Bool?
    /** friendly label */
    public var label: String?
    /** device make */
    public var make: String?
    /** device model */
    public var model: String?
    /** device serial */
    public var serialNumber: String?
    /** firmware version */
    public var version: String?
    /** ip address */
    public var ipAddress: String?
    /** mac address */
    public var macAdddress: String?
    /** Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** technology notes */
    public var notes: String?
    /** device location relative to location */
    public var location: String?
    /** extended status details */
    public var statusDetail: String?
    /** Created */
    public var created: Date?
    /** Updated */
    public var updated: Date?
    /** Last time contact with device was attempted */
    public var lastChecked: Date?
    /** Last time contact with the device was made */
    public var lastSeen: Date?
    /** Last time a change was recorded */
    public var lastChanged: Date?
    /** Refernce number */
    public var pciSscRefNo: String?
    /** dependencies */
    public var ptsDeviceDependencies: String?
    /** list */
    public var appPaDssListed: Bool?
    /** expiration */
    public var paDdsExpireDate: Date?
    public var metadataValues: CustomerTechnologyMetadata?
    /** PCI compliance status */
    public var pciCompliant: String?
    /** Monitoring policy */
    public var policy: String?
    /** Status */
    public var status: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["parent_id"] = self.parentId
        nillableDictionary["customer_id"] = self.customerId
        nillableDictionary["customer_location_id"] = self.customerLocationId
        nillableDictionary["org_id"] = self.orgId
        nillableDictionary["nickname"] = self.nickname
        nillableDictionary["type"] = self.type
        nillableDictionary["critical"] = self.critical
        nillableDictionary["active"] = self.active
        nillableDictionary["label"] = self.label
        nillableDictionary["make"] = self.make
        nillableDictionary["model"] = self.model
        nillableDictionary["serial_number"] = self.serialNumber
        nillableDictionary["version"] = self.version
        nillableDictionary["ip_address"] = self.ipAddress
        nillableDictionary["mac_adddress"] = self.macAdddress
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["notes"] = self.notes
        nillableDictionary["location"] = self.location
        nillableDictionary["status_detail"] = self.statusDetail
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()
        nillableDictionary["last_checked"] = self.lastChecked?.encodeToJSON()
        nillableDictionary["last_seen"] = self.lastSeen?.encodeToJSON()
        nillableDictionary["last_changed"] = self.lastChanged?.encodeToJSON()
        nillableDictionary["pci_ssc_ref_no"] = self.pciSscRefNo
        nillableDictionary["pts_device_dependencies"] = self.ptsDeviceDependencies
        nillableDictionary["app_pa_dss_listed"] = self.appPaDssListed
        nillableDictionary["pa_dds_expire_date"] = self.paDdsExpireDate?.encodeToJSON()
        nillableDictionary["metadata_values"] = self.metadataValues?.encodeToJSON()
        nillableDictionary["pci_compliant"] = self.pciCompliant
        nillableDictionary["policy"] = self.policy
        nillableDictionary["status"] = self.status

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

