//
// CustomForm.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Mapping of field names to field types */
open class CustomForm: JSONEncodable {

    public var id: String?
    public var name: String?
    public var type: String?
    public var orgTeamIds: [String]?
    public var created: Date?
    public var updated: Date?
    public var fields: [CustomFormField]?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["type"] = self.type
        nillableDictionary["org_team_ids"] = self.orgTeamIds?.encodeToJSON()
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()
        nillableDictionary["fields"] = self.fields?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

