//
// CustomerLocationMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Extended customer location attributes/customer location metadata */
open class CustomerLocationMetadata: JSONEncodable {

    /** Location Technology Notes */
    public var locationTechnologyNotes: String?
    /** Unique Connectivity Details */
    public var uniqueAspectsThatAffectConnectivity: String?
    /** Terminal ID (TID) */
    public var terminalIdentificationNumber: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["location_technology_notes"] = self.locationTechnologyNotes
        nillableDictionary["unique_aspects_that_affect_connectivity"] = self.uniqueAspectsThatAffectConnectivity
        nillableDictionary["terminal_identification_number"] = self.terminalIdentificationNumber

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

