//
// Customer.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Customer: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Business name */
    public var name: String?
    /** Business legal name */
    public var nameLegal: String?
    /** Address 1 */
    public var street1: String?
    /** Address 2 */
    public var street2: String?
    /** City */
    public var city: String?
    /** State/Province (2 char code) */
    public var state: String?
    /** ZIP/Postal Code */
    public var zipcode: String?
    /** Email */
    public var email: String?
    /** Phone */
    public var phone: String?
    /** Unique ID / Primary Key of this customer within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** Industry */
    public var industry: String?
    /** Status */
    public var status: String?
    /** Created */
    public var created: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["name_legal"] = self.nameLegal
        nillableDictionary["street_1"] = self.street1
        nillableDictionary["street_2"] = self.street2
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["zipcode"] = self.zipcode
        nillableDictionary["email"] = self.email
        nillableDictionary["phone"] = self.phone
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["industry"] = self.industry
        nillableDictionary["status"] = self.status
        nillableDictionary["created"] = self.created?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

