//
// CustomerLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CustomerLocation: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** The primary key of the related *Customer* */
    public var customerId: String?
    /** Address 1 */
    public var street1: String?
    /** Address 2 */
    public var street2: String?
    /** City */
    public var city: String?
    /** State/Province (2 char code) */
    public var state: String?
    /** ZIP/Postal Code */
    public var zipcode: String?
    /** Latitude */
    public var latitude: Double?
    /** Longitude */
    public var longitude: Double?
    /** Phone */
    public var phone: String?
    /** Informal reference, an alias */
    public var siteName: String?
    /** Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** Notes */
    public var notes: String?
    public var customForms: CustomFormDataList?
    /** File attachments by category */
    public var files: [[UploadFile]]?
    /** Customer Identification Number(s) (MIDs) */
    public var customerIds: [String]?
    public var metadataValues: CustomerLocationMetadata?
    public var technology: CustomerTechnologySummary?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["customer_id"] = self.customerId
        nillableDictionary["street_1"] = self.street1
        nillableDictionary["street_2"] = self.street2
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["zipcode"] = self.zipcode
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["phone"] = self.phone
        nillableDictionary["site_name"] = self.siteName
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["notes"] = self.notes
        nillableDictionary["custom_forms"] = self.customForms?.encodeToJSON()
        nillableDictionary["files"] = self.files?.encodeToJSON()
        nillableDictionary["customer_ids"] = self.customerIds?.encodeToJSON()
        nillableDictionary["metadata_values"] = self.metadataValues?.encodeToJSON()
        nillableDictionary["technology"] = self.technology?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

