//
// CustomFormField.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Describes a field in a custom form */
open class CustomFormField: JSONEncodable {

    public var id: String?
    public var type: String?
    public var name: String?
    public var label: String?
    public var defaultValue: String?
    public var listItems: HashMapOfStrings?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["type"] = self.type
        nillableDictionary["name"] = self.name
        nillableDictionary["label"] = self.label
        nillableDictionary["default_value"] = self.defaultValue
        nillableDictionary["list_items"] = self.listItems?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

