//
// CustomerTechnologyMetadata.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Extended customer technology attributes/customer technology metadata */
open class CustomerTechnologyMetadata: JSONEncodable {

    /** Download consumed */
    public var downloadConsumed: Float?
    /** Upload consumed */
    public var uploadConsumed: Float?
    /** Network presence relative to POS */
    public var networkAtPosStation: Bool?
    /** Presence of EMV reader or NFC communication */
    public var posEmvNfc: Bool?
    /** POS software org */
    public var posOrg: String?
    /** Presence of electrical */
    public var powerAtPosStation: Bool?
    /** Provisioned terminal ID */
    public var terminalId: String?
    /** Unique device id */
    public var uuid: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["download_consumed"] = self.downloadConsumed
        nillableDictionary["upload_consumed"] = self.uploadConsumed
        nillableDictionary["network_at_pos_station"] = self.networkAtPosStation
        nillableDictionary["pos_emv_nfc"] = self.posEmvNfc
        nillableDictionary["pos_org"] = self.posOrg
        nillableDictionary["power_at_pos_station"] = self.powerAtPosStation
        nillableDictionary["terminal_id"] = self.terminalId
        nillableDictionary["uuid"] = self.uuid

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

