//
// CustomerCreateRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class CustomerCreateRequest: JSONEncodable {

    public var customer: Customer?
    public var customerUser: CustomerUser?
    public var customerLocation: CustomerLocation?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["customer"] = self.customer?.encodeToJSON()
        nillableDictionary["customer_user"] = self.customerUser?.encodeToJSON()
        nillableDictionary["customer_location"] = self.customerLocation?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

