//
// CustomFormDataList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Dictionary of &#x60;CustomFormData&#x60; objects hashed by form ID. This serves as a means to associate additional data with  an object: each custom form is an array of fields, and when a custom form is applied to an object each field gets  assigned a value specific to that object. The &#x60;id&#x60; property is an example: it will actually be an ID of a form */
open class CustomFormDataList: JSONEncodable {


    public var additionalProperties: [AnyHashable:CustomFormData] = [:]

    public init() {}

    public subscript(key: AnyHashable) -> CustomFormData? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }
    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()

        for (key, value) in additionalProperties {
            if let key = key as? String {
               nillableDictionary[key] = value
            }
        }

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

