//
// CustomFormData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** Dictionary mapping all the field keys from a custom form to the values for those fields for this object. The &#x60;field&#x60; property name is an example; the actual property names will depend on the fields define in this form. */
open class CustomFormData: JSONEncodable {

    public var field: String?

    public var additionalProperties: [AnyHashable:String] = [:]

    public init() {}

    public subscript(key: AnyHashable) -> String? {
        get {
            if let value = additionalProperties[key] {
                return value
            }
            return nil
        }

        set {
            additionalProperties[key] = newValue
        }
    }
    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["field"] = self.field

        for (key, value) in additionalProperties {
            if let key = key as? String {
               nillableDictionary[key] = value
            }
        }

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

