//
// Emoticon.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Emoticon: JSONEncodable {

    /** Name/label of emoticon */
    public var lbl: String?
    /** The text in chat that is replaced with the emoticon */
    public var shorthand: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["lbl"] = self.lbl
        nillableDictionary["shorthand"] = self.shorthand

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

