//
// IssueLog.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class IssueLog: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Related *Issue* primary key */
    public var issuesId: String?
    /** Differences */
    public var diffLog: String?
    /** Notes */
    public var notes: String?
    /** Created */
    public var created: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["issues_id"] = self.issuesId
        nillableDictionary["diff_log"] = self.diffLog
        nillableDictionary["notes"] = self.notes
        nillableDictionary["created"] = self.created?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

