//
// IssueChatHistory.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class IssueChatHistory: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Object Id */
    public var objectId: String?
    /** Object Scope */
    public var objectScope: String?
    /** Chat Type */
    public var chatType: Int32?
    /** Chat Status */
    public var chatStatus: Int32?
    /** Billing Status */
    public var billingStatus: Int32?
    /** Title */
    public var title: String?
    /** Sub Title */
    public var subtitle: String?
    /** Duration Plus */
    public var durationPlus: Int32?
    /** Duration */
    public var duration: Int32?
    public var transcript: IssueChatHistoryTranscript?
    /** Eternal rpid */
    public var externalRpid: String?
    /** Eternal lpid */
    public var externalLpid: String?
    /** Eternal Id */
    public var externalId: String?
    /** Created */
    public var created: Date?
    /** Updated */
    public var updated: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["object_id"] = self.objectId
        nillableDictionary["object_scope"] = self.objectScope
        nillableDictionary["chat_type"] = self.chatType?.encodeToJSON()
        nillableDictionary["chat_status"] = self.chatStatus?.encodeToJSON()
        nillableDictionary["billing_status"] = self.billingStatus?.encodeToJSON()
        nillableDictionary["title"] = self.title
        nillableDictionary["subtitle"] = self.subtitle
        nillableDictionary["duration_plus"] = self.durationPlus?.encodeToJSON()
        nillableDictionary["duration"] = self.duration?.encodeToJSON()
        nillableDictionary["transcript"] = self.transcript?.encodeToJSON()
        nillableDictionary["external_rpid"] = self.externalRpid
        nillableDictionary["external_lpid"] = self.externalLpid
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

