//
// Issue.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Issue: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Reference number */
    public var referenceNum: String?
    /** Org Cases/Tickets */
    public var remoteId: String?
    /** Related *Customer* primary key */
    public var customerId: String?
    /** Related *Customer* name */
    public var customerName: String?
    /** Related *Customer* email */
    public var customerEmail: String?
    /** Related *CustomerLocation* primary key */
    public var customerLocationId: String?
    /** Related *CustomerLocation* name */
    public var customerLocationName: String?
    /** Related *CustomerUser* primary key */
    public var customerUserId: String?
    /** Related *CustomerUser* name */
    public var customerUserName: String?
    /** Related *CustomerUser* email */
    public var customerUserEmail: String?
    /** Related *Admin User* primary key */
    public var userId: String?
    /** Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** Type */
    public var type: String?
    /** Category */
    public var category: String?
    /** Details */
    public var details: String?
    /** Status */
    public var status: String?
    /** Job type */
    public var job: String?
    /** Resolution */
    public var resolution: String?
    /** Created */
    public var created: Date?
    /** Updated */
    public var updated: Date?
    /** Technician job scheduled */
    public var scheduledTime: Date?
    /** Technician en-route for job */
    public var enrouteTime: Date?
    /** Technician arrived at job */
    public var arrivalTime: Date?
    /** Technician departed job */
    public var departureTime: Date?
    /** IDR ISQ */
    public var idrIsq: String?
    /** IDR Process */
    public var idrProcess: String?
    /** IDR Resolution */
    public var idrResolution: String?
    /** Tech Support Minutes */
    public var techSupportMinutes: Int32?
    /** Issue special notes (empty if no access) */
    public var specialNotes: String?
    /** Unmanaged by Boomtown SLA */
    public var unmanaged: Bool?
    public var metadataValues: IssueMetadata?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["reference_num"] = self.referenceNum
        nillableDictionary["remote_id"] = self.remoteId
        nillableDictionary["customer_id"] = self.customerId
        nillableDictionary["customer_name"] = self.customerName
        nillableDictionary["customer_email"] = self.customerEmail
        nillableDictionary["customer_location_id"] = self.customerLocationId
        nillableDictionary["customer_location_name"] = self.customerLocationName
        nillableDictionary["customer_user_id"] = self.customerUserId
        nillableDictionary["customer_user_name"] = self.customerUserName
        nillableDictionary["customer_user_email"] = self.customerUserEmail
        nillableDictionary["user_id"] = self.userId
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["type"] = self.type
        nillableDictionary["category"] = self.category
        nillableDictionary["details"] = self.details
        nillableDictionary["status"] = self.status
        nillableDictionary["job"] = self.job
        nillableDictionary["resolution"] = self.resolution
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()
        nillableDictionary["scheduled_time"] = self.scheduledTime?.encodeToJSON()
        nillableDictionary["enroute_time"] = self.enrouteTime?.encodeToJSON()
        nillableDictionary["arrival_time"] = self.arrivalTime?.encodeToJSON()
        nillableDictionary["departure_time"] = self.departureTime?.encodeToJSON()
        nillableDictionary["idr_isq"] = self.idrIsq
        nillableDictionary["idr_process"] = self.idrProcess
        nillableDictionary["idr_resolution"] = self.idrResolution
        nillableDictionary["tech_support_minutes"] = self.techSupportMinutes?.encodeToJSON()
        nillableDictionary["special_notes"] = self.specialNotes
        nillableDictionary["unmanaged"] = self.unmanaged
        nillableDictionary["metadata_values"] = self.metadataValues?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

