//
// Org.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Org: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Business name */
    public var name: String?
    /** Business legal name */
    public var nameLegal: String?
    /** Hashtag nickname for group mentions in chat */
    public var nickname: String?
    /** The chatunication channel id */
    public var chatId: String?
    /** Description */
    public var description: String?
    /** Address 1 */
    public var street1: String?
    /** Address 2 */
    public var street2: String?
    /** City */
    public var city: String?
    /** State/Province (2 char code) */
    public var state: String?
    /** ZIP/Postal Code */
    public var zipcode: String?
    /** Latitude */
    public var latitude: Float?
    /** Longitude */
    public var longitude: Float?
    /** Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** Default OrgTeam&#39;s id */
    public var defaultOrgTeamId: String?
    /** Email */
    public var email: String?
    /** Phone */
    public var phone: String?
    /** Web site (URL) */
    public var website: String?
    /** Avatar (URL) */
    public var avatar: String?
    /** Created */
    public var created: Date?
    /** Updated */
    public var updated: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["name"] = self.name
        nillableDictionary["name_legal"] = self.nameLegal
        nillableDictionary["nickname"] = self.nickname
        nillableDictionary["chat_id"] = self.chatId
        nillableDictionary["description"] = self.description
        nillableDictionary["street_1"] = self.street1
        nillableDictionary["street_2"] = self.street2
        nillableDictionary["city"] = self.city
        nillableDictionary["state"] = self.state
        nillableDictionary["zipcode"] = self.zipcode
        nillableDictionary["latitude"] = self.latitude
        nillableDictionary["longitude"] = self.longitude
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["default_org_team_id"] = self.defaultOrgTeamId
        nillableDictionary["email"] = self.email
        nillableDictionary["phone"] = self.phone
        nillableDictionary["website"] = self.website
        nillableDictionary["avatar"] = self.avatar
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

