//
// OrgReportItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class OrgReportItem: JSONEncodable {

    public var issueID: String?
    public var referenceNum: String?
    public var orgCasesTickets: String?
    public var issueStatus: String?
    public var jobStatus: String?
    public var adminUserOrgTeamUser: String?
    public var org: String?
    public var issueType: String?
    public var workOrderType: String?
    public var issueCategory: String?
    public var customerName: String?
    public var customerLocationSiteName: String?
    public var customerLocationStreet1: String?
    public var customerLocationStreet2: String?
    public var city: String?
    public var state: String?
    public var zipcode: String?
    public var country: String?
    public var timeZoneOfScheduledActionDateAndTime: String?
    public var issueCreationDateAndTime: Date?
    public var dateAndTimeScheduledByProjectManager: Date?
    public var scheduledDateAndTime: Date?
    public var startDateAndTime: Date?
    public var resolvedDateAndTime: Date?
    public var remoteWaitTime: String?
    public var serviceTime: Float?
    public var resolution: String?
    public var NPS: Float?
    public var technicianRating: Float?
    public var total: Float?
    public var paymentStatus: String?
    public var specialNotes: String?
    public var techSupportMinutes: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Issue ID"] = self.issueID
        nillableDictionary["Reference Num"] = self.referenceNum
        nillableDictionary["Org Cases/Tickets"] = self.orgCasesTickets
        nillableDictionary["Issue Status"] = self.issueStatus
        nillableDictionary["Job Status"] = self.jobStatus
        nillableDictionary["Admin User / Org Team User"] = self.adminUserOrgTeamUser
        nillableDictionary["Org"] = self.org
        nillableDictionary["Issue Type"] = self.issueType
        nillableDictionary["Work Order Type"] = self.workOrderType
        nillableDictionary["Issue Category"] = self.issueCategory
        nillableDictionary["Customer Name"] = self.customerName
        nillableDictionary["Customer Location Site Name"] = self.customerLocationSiteName
        nillableDictionary["Customer Location Street 1"] = self.customerLocationStreet1
        nillableDictionary["Customer Location Street 2"] = self.customerLocationStreet2
        nillableDictionary["City"] = self.city
        nillableDictionary["State"] = self.state
        nillableDictionary["Zipcode"] = self.zipcode
        nillableDictionary["Country"] = self.country
        nillableDictionary["Time Zone of Scheduled/Action Date and Time"] = self.timeZoneOfScheduledActionDateAndTime
        nillableDictionary["Issue Creation Date and Time"] = self.issueCreationDateAndTime?.encodeToJSON()
        nillableDictionary["Date and Time Scheduled by Project Manager"] = self.dateAndTimeScheduledByProjectManager?.encodeToJSON()
        nillableDictionary["Scheduled Date and Time"] = self.scheduledDateAndTime?.encodeToJSON()
        nillableDictionary["Start Date and Time"] = self.startDateAndTime?.encodeToJSON()
        nillableDictionary["Resolved Date and Time"] = self.resolvedDateAndTime?.encodeToJSON()
        nillableDictionary["Remote Wait Time"] = self.remoteWaitTime
        nillableDictionary["Service Time"] = self.serviceTime
        nillableDictionary["Resolution"] = self.resolution
        nillableDictionary["NPS"] = self.NPS
        nillableDictionary["Technician Rating"] = self.technicianRating
        nillableDictionary["Total"] = self.total
        nillableDictionary["Payment Status"] = self.paymentStatus
        nillableDictionary["Special Notes"] = self.specialNotes
        nillableDictionary["Tech Support Minutes"] = self.techSupportMinutes

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

