//
// OrgUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class OrgUser: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Email */
    public var email: String?
    /** First name */
    public var firstName: String?
    /** Last name */
    public var lastName: String?
    /** Mobile/SMS phone */
    public var smsNumber: String?
    /** Unique ID / Primary Key of this object within a third-party system, used to correlate with the callee&#39;s data */
    public var externalId: String?
    /** Time zone */
    public var timeZone: String?
    /** Status */
    public var status: String?
    /** Phone support availability */
    public var present: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["email"] = self.email
        nillableDictionary["first_name"] = self.firstName
        nillableDictionary["last_name"] = self.lastName
        nillableDictionary["sms_number"] = self.smsNumber
        nillableDictionary["external_id"] = self.externalId
        nillableDictionary["time_zone"] = self.timeZone
        nillableDictionary["status"] = self.status
        nillableDictionary["present"] = self.present

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

