//
// PhoneResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PhoneResponse: JSONEncodable {

    /** Indicates success of the operation */
    public var success: Bool?
    public var currentServerTime: Date?
    /** ID of the matched / created Issue object */
    public var issueId: String?
    /** Deprecated */
    public var message: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["success"] = self.success
        nillableDictionary["current_server_time"] = self.currentServerTime?.encodeToJSON()
        nillableDictionary["issue_id"] = self.issueId
        nillableDictionary["message"] = self.message

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

