//
// ReportingKPITimeOnsiteByLocationResponseResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReportingKPITimeOnsiteByLocationResponseResults: JSONEncodable {

    public var orgId: String?
    public var org: String?
    public var orgTeamId: String?
    public var orgTeam: String?
    public var siteId: String?
    public var siteName: String?
    public var onsiteIssues: Double?
    public var totalTimeOnsite: Float?
    public var averageTimeOnsite: Float?
    public var timeInterval: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Org Id"] = self.orgId
        nillableDictionary["Org"] = self.org
        nillableDictionary["Org Team Id"] = self.orgTeamId
        nillableDictionary["Org Team"] = self.orgTeam
        nillableDictionary["Site Id"] = self.siteId
        nillableDictionary["Site Name"] = self.siteName
        nillableDictionary["# Onsite Issues"] = self.onsiteIssues
        nillableDictionary["Total Time Onsite"] = self.totalTimeOnsite
        nillableDictionary["Average Time Onsite"] = self.averageTimeOnsite
        nillableDictionary["Time Interval"] = self.timeInterval

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

