//
// ReportingKPIIssuesByAgeResponseResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReportingKPIIssuesByAgeResponseResults: JSONEncodable {

    public var orgId: String?
    public var org: String?
    public var orgTeamId: String?
    public var orgTeam: String?
    public var last24Hrs: Double?
    public var last7Days: Double?
    public var last30Days: Double?
    public var allTime: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Org Id"] = self.orgId
        nillableDictionary["Org"] = self.org
        nillableDictionary["Org Team Id"] = self.orgTeamId
        nillableDictionary["Org Team"] = self.orgTeam
        nillableDictionary["Last 24 hrs"] = self.last24Hrs
        nillableDictionary["Last 7 days"] = self.last7Days
        nillableDictionary["Last 30 days"] = self.last30Days
        nillableDictionary["All Time"] = self.allTime

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

