//
// ReportingKPIOpenIssuesResponseResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReportingKPIOpenIssuesResponseResults: JSONEncodable {

    public var orgId: String?
    public var orgTeamId: String?
    public var customer: String?
    public var siteName: String?
    public var type: String?
    public var category: String?
    public var status: String?
    public var claimed: Double?
    public var created: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Org Id"] = self.orgId
        nillableDictionary["Org Team Id"] = self.orgTeamId
        nillableDictionary["Customer"] = self.customer
        nillableDictionary["Site Name"] = self.siteName
        nillableDictionary["Type"] = self.type
        nillableDictionary["Category"] = self.category
        nillableDictionary["Status"] = self.status
        nillableDictionary["Claimed"] = self.claimed
        nillableDictionary["Created"] = self.created

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

