//
// ReportingKPIAverageTimeToScheduledResponseResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReportingKPIAverageTimeToScheduledResponseResults: JSONEncodable {

    public var orgId: String?
    public var org: String?
    public var orgTeamId: String?
    public var orgTeam: String?
    public var category: String?
    public var averageDaysToScheduled: Float?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Org Id"] = self.orgId
        nillableDictionary["Org"] = self.org
        nillableDictionary["Org Team Id"] = self.orgTeamId
        nillableDictionary["Org Team"] = self.orgTeam
        nillableDictionary["Category"] = self.category
        nillableDictionary["Average Days To Scheduled"] = self.averageDaysToScheduled

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

