//
// ReportingKPIOrgOwnedIssuesResponseResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReportingKPIOrgOwnedIssuesResponseResults: JSONEncodable {

    public var orgId: String?
    public var org: String?
    public var orgTeamId: String?
    public var orgTeam: String?
    public var supportIssues: Double?
    public var workOrderIssues: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Org Id"] = self.orgId
        nillableDictionary["Org"] = self.org
        nillableDictionary["Org Team Id"] = self.orgTeamId
        nillableDictionary["Org Team"] = self.orgTeam
        nillableDictionary["# Support Issues"] = self.supportIssues
        nillableDictionary["# Work Order Issues"] = self.workOrderIssues

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

