//
// ReportingKPIIssuesRemoteVsOnsiteResponseResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class ReportingKPIIssuesRemoteVsOnsiteResponseResults: JSONEncodable {

    public var orgId: String?
    public var org: String?
    public var orgTeamId: String?
    public var orgTeam: String?
    public var remoteIssues: Double?
    public var remote: Float?
    public var onsiteIssues: Double?
    public var onsite: Float?
    public var totalIssues: Double?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Org Id"] = self.orgId
        nillableDictionary["Org"] = self.org
        nillableDictionary["Org Team Id"] = self.orgTeamId
        nillableDictionary["Org Team"] = self.orgTeam
        nillableDictionary["# Remote Issues"] = self.remoteIssues
        nillableDictionary["% Remote"] = self.remote
        nillableDictionary["# Onsite Issues"] = self.onsiteIssues
        nillableDictionary["% Onsite"] = self.onsite
        nillableDictionary["# Total Issues"] = self.totalIssues

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

