//
// Shipment.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class Shipment: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Description */
    public var description: String?
    /** Pieces */
    public var pieces: String?
    /** Carrier */
    public var carrier: String?
    /** Carrier Tracking Number */
    public var carrierTracking: String?
    /** ETA */
    public var estimatedArrival: Date?
    /** Status */
    public var status: String?
    /** Created */
    public var created: Date?
    /** Updated */
    public var updated: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["description"] = self.description
        nillableDictionary["pieces"] = self.pieces
        nillableDictionary["carrier"] = self.carrier
        nillableDictionary["carrier_tracking"] = self.carrierTracking
        nillableDictionary["estimated_arrival"] = self.estimatedArrival?.encodeToJSON()
        nillableDictionary["status"] = self.status
        nillableDictionary["created"] = self.created?.encodeToJSON()
        nillableDictionary["updated"] = self.updated?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

