//
// TechnicianReportItem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class TechnicianReportItem: JSONEncodable {

    public var technicianID: String?
    public var technicianName: String?
    public var officePhone: String?
    public var cellPhone: String?
    public var eMail: String?
    public var technicianStreet1: String?
    public var technicianStreet2: String?
    public var city: String?
    public var state: String?
    public var zipcode: String?
    public var country: String?
    public var timeZone: String?
    public var nearestMetro: String?
    public var hourlyRate: Float?
    public var travelRadius: Float?
    public var averageTravelDistanceToCustomerLocationForCompletedWorkOrders: Float?
    public var status: String?
    public var ofJobsAdvertised: Int32?
    public var ofJobsDeclined: Int32?
    public var ofJobsNoResponse: Int32?
    public var ofJobsCanceled: Int32?
    public var ofJobsCompleted: Int32?
    public var averageTechnicianRating: Float?
    public var averageNPS: Float?
    public var averageMargin_: Float?
    public var onTimePerformance: Float?
    public var dateOfLastWorkOrder: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Technician ID"] = self.technicianID
        nillableDictionary["Technician Name"] = self.technicianName
        nillableDictionary["Office Phone"] = self.officePhone
        nillableDictionary["Cell Phone"] = self.cellPhone
        nillableDictionary["E-mail"] = self.eMail
        nillableDictionary["Technician Street 1"] = self.technicianStreet1
        nillableDictionary["Technician Street 2"] = self.technicianStreet2
        nillableDictionary["City"] = self.city
        nillableDictionary["State"] = self.state
        nillableDictionary["Zipcode"] = self.zipcode
        nillableDictionary["Country"] = self.country
        nillableDictionary["Time Zone"] = self.timeZone
        nillableDictionary["Nearest Metro"] = self.nearestMetro
        nillableDictionary["Hourly Rate"] = self.hourlyRate
        nillableDictionary["Travel Radius"] = self.travelRadius
        nillableDictionary["Average Travel Distance to Customer Location for Completed Work Orders"] = self.averageTravelDistanceToCustomerLocationForCompletedWorkOrders
        nillableDictionary["Status"] = self.status
        nillableDictionary["# of Jobs Advertised"] = self.ofJobsAdvertised?.encodeToJSON()
        nillableDictionary["# of Jobs Declined"] = self.ofJobsDeclined?.encodeToJSON()
        nillableDictionary["# of Jobs No Response"] = self.ofJobsNoResponse?.encodeToJSON()
        nillableDictionary["# of Jobs Canceled"] = self.ofJobsCanceled?.encodeToJSON()
        nillableDictionary["# of Jobs Completed"] = self.ofJobsCompleted?.encodeToJSON()
        nillableDictionary["Average Technician Rating"] = self.averageTechnicianRating
        nillableDictionary["Average NPS"] = self.averageNPS
        nillableDictionary["Average Margin %"] = self.averageMargin_
        nillableDictionary["On Time Performance"] = self.onTimePerformance
        nillableDictionary["Date of Last Work Order"] = self.dateOfLastWorkOrder?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

