//
// UploadFile.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class UploadFile: JSONEncodable {

    /** Primary key */
    public var id: String?
    /** Owner entity */
    public var object: String?
    /** Owner entity id */
    public var objectId: String?
    /** MIME type */
    public var type: String?
    /** Download URL */
    public var file: String?
    /** Filesize in bytes */
    public var size: Int32?
    /** Original filename */
    public var name: String?
    /** Category */
    public var tag: String?
    /** Additional notes */
    public var notes: String?
    /** Preview URL, replace trailing dimensions as needed */
    public var thumbnail: String?
    /** Created */
    public var created: Date?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["object"] = self.object
        nillableDictionary["object_id"] = self.objectId
        nillableDictionary["type"] = self.type
        nillableDictionary["file"] = self.file
        nillableDictionary["size"] = self.size?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["tag"] = self.tag
        nillableDictionary["notes"] = self.notes
        nillableDictionary["thumbnail"] = self.thumbnail
        nillableDictionary["created"] = self.created?.encodeToJSON()

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

